### ISSUE TITLE
exc_illegal_opcode on mcst-lcc 1.27 (OSL-8)

### ISSUE THREAD

**Issue by r-a-sattarov** [helce/LuaJIT#3]
```
exc_illegal_opcode at 0x45555999af30 

0x000045555999af30 in lj_BC_IFUNCV () from /usr/lib64/xrLuaJIT.so
(gdb) bt
#0  0x000045555999af30 in lj_BC_IFUNCV () from /usr/lib64/xrLuaJIT.so
#1  0x0000455558c2b8c8 in luajit::open_lib (L=0x1dc9000, module_name=0x455558d99930 "", function=0x4555599a6018 <luaopen_base>)
    at /home/user/dev/xray-16_20-Mar-2024/src/xrScriptEngine/script_engine.cpp:920
#2  0x0000455558c145a0 in CScriptEngine::init (this=0x1dc6208, exporterFunc=0x4555825461b0 <CResourceManager::LS_Load()::{lambda(lua_State*)#1}::_FUN(lua_State*)>, 
    loadGlobalNamespace=false) at /home/user/dev/xray-16_20-Mar-2024/src/xrScriptEngine/script_engine.cpp:973
#3  0x00004555825402d0 in CResourceManager::LS_Load () at /home/user/dev/xray-16_20-Mar-2024/src/Layers/xrRenderGL/glResourceManager_Scripting.cpp:413
#4  0x0000455581e63cc8 in CResourceManager::OnDeviceCreate (this=0x1dc5df0, F=0x1721030) at /home/user/dev/xray-16_20-Mar-2024/src/Layers/xrRender/ResourceManager_Loader.cpp:59
#5  0x0000455581e64b78 in CResourceManager::OnDeviceCreate (this=0x1dc5df0, 
    shName=0xc2deffff8e30 "\\home\\user\\.local\\share\\GSC Game World\\S.T.A.L.K.E.R. - Call of Pripyat\\gamedata\\shaders.xr")
    at /home/user/dev/xray-16_20-Mar-2024/src/Layers/xrRender/ResourceManager_Loader.cpp:143
#6  0x00004555817c2c28 in D3DXRenderBase::OnDeviceCreate (this=0x455582b85ff0 <RImplementation>, 
    shName=0xc2deffff8e30 "\\home\\user\\.local\\share\\GSC Game World\\S.T.A.L.K.E.R. - Call of Pripyat\\gamedata\\shaders.xr")
    at /home/user/dev/xray-16_20-Mar-2024/src/Layers/xrRender/D3DXRenderBase.cpp:144
#7  0x00004555822ab598 in CRender::OnDeviceCreate (this=0x455582b85ff0 <RImplementation>, 
    shName=0xc2deffff8e30 "\\home\\user\\.local\\share\\GSC Game World\\S.T.A.L.K.E.R. - Call of Pripyat\\gamedata\\shaders.xr")
    at /home/user/dev/xray-16_20-Mar-2024/src/Layers/xrRender_R2/r2.cpp:221
#8  0x0000455556122aa8 in CRenderDevice::Create (this=0x4555566a9fa0 <Device>) at /home/user/dev/xray-16_20-Mar-2024/src/xrEngine/Device_create.cpp:45
#9  0x0000455555fdd6b0 in CApplication::CApplication (commandLine=0x14ed0 "") at /home/user/dev/xray-16_20-Mar-2024/src/xrEngine/x_ray.cpp:356
#10 0x00000000000134c8 in entry_point (commandLine=0x14ed0 "") at /home/user/dev/xray-16_20-Mar-2024/src/xr_3da/entry_point.cpp:27
#11 0x0000000000013978 in main (argc=1, argv=0xc2deffffd208) at /home/user/dev/xray-16_20-Mar-2024/src/xr_3da/entry_point.cpp:84
```

**Comment by helce** [comment]
Проверяй. Вспомнил, что я это даже оттестил когда-то.
